### ISSUE TITLE
Half drag like inbox app?

### ISSUE THREAD

**Issue by Swisyn** [thesurix/gesture-recycler#1]
Thank you for this great lib. 

Is it possible to do half drag implementation like the Google's Inbox app. From left to right or right to left to show custom layout. 

![outlook-android-apk](https://cloud.githubusercontent.com/assets/6234115/13988713/da922c1e-f115-11e5-896c-049727bdda3f.png)

**Comment by thesurix** [comment]
Thanks!

Now it is not possible. I will try to add this feature in next updates. 
I think there are two possible solutions. First, by custom swipe animation strategies. You will get callback method like this:

``` java
onViewDraw(final Canvas c, final RecyclerView recyclerView, final RecyclerView.ViewHolder viewHolder, final float dX, final float dY ....)
```

so you will be able to draw anything or by extended GestureViewHolder interface.

**Comment by krooq** [comment]
This is a great suggestion, it's definitely the next thing I tried to do after implementing this library :)

**Comment by thesurix** [comment]
@Swisyn 
You can check this feature in new release (v1.5.0)

**Comment by ramonsgds** [comment]
Hey, I looked at the new release but didn't find the method. How can I set it up so that it's swiped until the half of the view's width and after clicking on the backgroundView, I can programmatically call it to be swiped until the end (full width) and be removed?

**Comment by thesurix** [comment]
Hello, unfortunately this behavior is not supported now, you can only swipe entire item. By the way it is good idea for future releases, I will add it to TODO list.

**Comment by ramonsgds** [comment]
Do you think you can do it in a few days? I really need this feature and will have to look for another library since this awesome library you created does not support it :/

**Comment by thesurix** [comment]
Not really, I only work with this lib in my spare time. I think I need at least few weeks, it is not trivial case
