### ISSUE TITLE
Different layouts for different swipe direction

### ISSUE THREAD

**Issue by RomanAnchugov** [thesurix/gesture-recycler#12]
Do you plan to add this feature to your lib otherwise could you give an advise how to add this by myself?

**Comment by thesurix** [comment]
Could you describe your case? Do you mean different background view?

**Comment by RomanAnchugov** [comment]
Ok. For example a want to show one background layout when user swipes from left to right(exmpl delete gesture) and another layout when swipes right to left(exmpls add to favourites gesture) and also handle a different callbacks of this gstures.
As i see for now you library doesnt support handeling of different direction(left, right) gestures.
Do you plan to implement it in the future?)
Thank you!

**Comment by thesurix** [comment]
Ok, I get in now. With current version 1.7.0 it is not possible. You can play with `override fun onSelectedChanged()` and  `override fun onChildDraw()` methods in `GestureTouchHelperCallback` class, check swipe direction and hide/show appropriate background view. Good case for next feature, I will add it to my todo list.

**Comment by RomanAnchugov** [comment]
Nice advise, i'll try it. Great to hear it. Thank you😉

**Comment by thesurix** [comment]
Implemented in version 1.13.0
