### ISSUE TITLE
Support for Grid Layout Manager

### ISSUE THREAD

**Issue by ViktorSkabiak** [thesurix/gesture-recycler#13]
Does this library support GridLayoutManager instead of LinearLayoutManager?

**Comment by thesurix** [comment]
Sure, you can check example app: [GridRecyclerFragment.kt](https://github.com/thesurix/gesture-recycler/blob/master/example/src/main/java/com/thesurix/example/gesturerecycler/fragment/GridRecyclerFragment.kt)

**Comment by ViktorSkabiak** [comment]
> Sure, you can check example app: [GridRecyclerFragment.kt](https://github.com/thesurix/gesture-recycler/blob/master/example/src/main/java/com/thesurix/example/gesturerecycler/fragment/GridRecyclerFragment.kt)

Thanks
