### ISSUE TITLE
[QUESTION]: Can we stop the drag at some point and make a button?

### ISSUE THREAD

**Issue by Drjacky** [thesurix/gesture-recycler#15]
Can we stop the drag at some point and when the user releases the dragging, there will be a button, and then, after clicking on the button, the action invokes?

**Comment by thesurix** [comment]
@Drjacky 
I think it can be hard to achieve but you can use undo feature. Item can be released and then user can approve his choice (button with no action or user can cancel this action and then you can invoke undo function to revert last action)
