### ISSUE TITLE
Is there away to swipe to the left and not to the right?

### ISSUE THREAD

**Issue by Dtuckrez** [thesurix/gesture-recycler#5]
Just wanted to know if there is away I can swipe to the left and nor right?

**Comment by thesurix** [comment]
Hello
Sure, you can build **GestureManager** like below: 

> GestureManager gestureManager = new GestureManager.Builder(mRecyclerView)
>                 .setSwipeEnabled(true)
>                 .setGestureFlags(ItemTouchHelper.LEFT, /* drag flags */ 0)
>                 .build();

You can use **ItemTouchHelper.LEFT** in the first param to define swipe direction (I will split this method because now it is unclear)
