### ISSUE TITLE
Recyclerview item drag not woking if recyclierview is used inside ScrollView

### ISSUE THREAD

**Issue by pradeep2424** [thesurix/gesture-recycler#6]
I have few Edittexts and bellow that recylcerview. All these components are under Scrollview.
If I try to drag recyclerview item down, recyclerview list is not scrolling to drop an item.
If I remove Scrollview placed then this works fine.

**Comment by thesurix** [comment]
I am able to scroll with an item in layout like this:
```xml
 <ScrollView xmlns:android="http://schemas.android.com/apk/res/android">
        <LinearLayout >
          <EditText />
          <EditText />
         <EditText />
         <EditText />
         <android.support.v7.widget.RecyclerView />
       </LinearLayout>
 </ScrollView>
```

but it is not recommended to use simple ScrollView... try to use android.support.v4.widget.NestedScrollView. I think it should work as expected.

**Comment by pradeep2424** [comment]
Yes I am using android.support.v4.widget.NestedScrollView. This works flawlessly.
Thank you.
