### ISSUE TITLE
How to get x,y coordinates when we drop item Onto another item ? not UP or Down .

### ISSUE THREAD

**Issue by Tejpandya** [thesurix/gesture-recycler#8]
Here we are rearranging the item's position , i want to achieve folder functionality with that . if  we  drag item onto  another , I want to generate folder for that two items .. is it possible with this lib ?

**Comment by thesurix** [comment]
This functionality is not supported currently. I think you should modify `GestureTouchHelperCallback.java` inside library and change/override `onMove()` and `onMoved()` methods (it should be possible to detect some kind of overlap between view holders).
